services:
  db:
    image: postgres:latest
    container_name: suapele_db
    restart: always
    environment:
      POSTGRES_USER: rafaelmachado18
      POSTGRES_PASSWORD: Mumias86
      POSTGRES_DB: suapeledb
    ports:
      - "5432:5432"

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: suapele_api
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=suapeledb;Username=rafaelmachado18;Password=Mumias86